import type { TftCatalogLine, TftSection } from "./types";

export const TFT_SECTION_LABELS: Record<TftSection, string> = {
  revenus: "Revenus",
  achats: "Achats marchandises",
  "charges-fixes": "Charges fixes",
  "charges-variables": "Charges variables",
  "impots-taxes": "Impots et taxes",
  personnel: "Personnel",
  investissements: "Investissements",
  financement: "Financement",
  is: "IS",
};

export const TFT_CATALOG: TftCatalogLine[] = [
  {
    id: "revenue-store",
    label: "CA boutique physique",
    section: "revenus",
    unit: "EUR/an HT",
    defaultEnabled: true,
    comment: "CA attendu en magasin sur 12 mois glissants.",
    computation: "annual-revenue-ht",
  },
  {
    id: "revenue-ecommerce",
    label: "CA e-commerce Shopify",
    section: "revenus",
    unit: "EUR/an HT",
    defaultEnabled: true,
    comment: "CA en ligne Shopify.",
    computation: "annual-revenue-ht",
  },
  {
    id: "purchase-rate",
    label: "Taux d'achat marchandises",
    section: "achats",
    unit: "%",
    defaultEnabled: true,
    comment: "Coef achat proche de 2,3, soit environ 43% du CA HT.",
    computation: "purchase-rate",
  },
  {
    id: "rent",
    label: "Loyer et charges locatives",
    section: "charges-fixes",
    unit: "EUR/an HT",
    defaultEnabled: true,
    comment: "Payable au debut de chaque trimestre d'activite.",
    computation: "quarterly-rent-ht",
  },
  ...[
    ["insurance", "Assurances", "annual-external-ht"],
    ["phone-internet", "Telephone, internet", "annual-external-ht"],
    ["utilities", "Eau, electricite, gaz", "annual-external-ht"],
    ["fuel-transport", "Carburant, transports", "annual-external-ht"],
    ["travel", "Frais de deplacement et hebergement", "annual-external-ht"],
    ["marketing", "Budget publicite et communication", "annual-external-ht"],
    ["accounting-legal", "Expert-comptable, avocats", "annual-external-ht"],
    ["bank-fees", "Frais bancaires hors CB", "annual-external-ht"],
    ["supplies", "Fournitures diverses", "annual-external-ht"],
    ["maintenance", "Entretien materiel et vetements", "annual-external-ht"],
    ["cleaning", "Nettoyage des locaux", "annual-external-ht"],
    ["health-insurance", "Mutuelle", "annual-external-ht"],
    ["subscriptions", "Autres abonnements", "annual-external-ht"],
  ].map(
    ([id, label, computation]) =>
      ({
        id,
        label,
        section: "charges-fixes",
        unit: "EUR/an HT",
        defaultEnabled: true,
        computation,
      }) as TftCatalogLine
  ),
  {
    id: "cb-fees",
    label: "Frais de paiement CB",
    section: "charges-variables",
    unit: "%",
    defaultEnabled: true,
    comment: "Stripe, Shopify ou terminal CB, calcule sur le CA TTC.",
    computation: "cb-fee-rate",
  },
  {
    id: "cfe",
    label: "CFE",
    section: "impots-taxes",
    unit: "EUR/an",
    defaultEnabled: true,
    comment: "Acompte en juin et solde en decembre.",
    computation: "cfe-annual",
  },
  {
    id: "personnel-start-month",
    label: "Mois de demarrage du 1er salarie",
    section: "personnel",
    unit: "mois 1-12",
    defaultEnabled: true,
    comment: "7 = juillet.",
    computation: "personnel-start-month",
  },
  {
    id: "salary-gross",
    label: "Salaire brut mensuel",
    section: "personnel",
    unit: "EUR/mois",
    defaultEnabled: true,
    computation: "salary-gross-monthly",
  },
  {
    id: "employer-charges",
    label: "Charges sociales mensuelles employeur",
    section: "personnel",
    unit: "EUR/mois",
    defaultEnabled: true,
    computation: "employer-charges-monthly",
  },
  {
    id: "intangibles",
    label: "Immobilisations incorporelles",
    section: "investissements",
    unit: "EUR HT",
    defaultEnabled: true,
    computation: "initial-investment-ht",
  },
  {
    id: "tangibles",
    label: "Immobilisations corporelles",
    section: "investissements",
    unit: "EUR HT",
    defaultEnabled: true,
    computation: "initial-investment-ht",
  },
  {
    id: "deposit",
    label: "Depot de garantie et caution bancaire",
    section: "investissements",
    unit: "EUR",
    defaultEnabled: true,
    comment: "Non soumis a TVA.",
    computation: "initial-deposit",
  },
  {
    id: "associate-contribution",
    label: "Apport des associes",
    section: "financement",
    unit: "EUR",
    defaultEnabled: true,
    computation: "associate-contribution",
  },
  {
    id: "bank-loan",
    label: "Emprunt bancaire capital",
    section: "financement",
    unit: "EUR",
    defaultEnabled: true,
    computation: "bank-loan-capital",
  },
  {
    id: "loan-rate",
    label: "Taux d'interet annuel emprunt",
    section: "financement",
    unit: "%",
    defaultEnabled: true,
    computation: "loan-annual-rate",
  },
  {
    id: "loan-duration",
    label: "Duree emprunt",
    section: "financement",
    unit: "annees",
    defaultEnabled: true,
    computation: "loan-duration-years",
  },
  {
    id: "corporate-tax-rate",
    label: "Taux IS",
    section: "is",
    unit: "%",
    defaultEnabled: true,
    comment: "Annee 1 : aucun acompte dans la V1.",
    computation: "corporate-tax-rate",
  },
];

export function getLinesBySection(section: TftSection): TftCatalogLine[] {
  return TFT_CATALOG.filter((line) => line.section === section);
}
